name = "pwxavengers-proxy"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Note: logpush requires paid plan, using console.log for free tier logging

[env.production]
name = "pwxavengers-proxy"

[env.staging]
name = "pwxavengers-proxy-staging"

# Routes configuration - uncomment and modify as needed
# routes = [
#   { pattern = "your-domain.com/api/*", zone_name = "your-domain.com" }
# ]

# Custom domain configuration - uncomment and modify as needed
# [[env.production.routes]]
# pattern = "api.your-domain.com/*"
# zone_name = "your-domain.com"

# Supabase configuration for caching
[vars]
SUPABASE_URL = "https://dnbytwnhwiemhbvlsrcd.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuYnl0d25od2llbWhidmxzcmNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MjM0MjgsImV4cCI6MjA3MDE5OTQyOH0.Vjwdm9nqcJ4KanIGXUxyQduLAAr090-FaO3vb3MhoUw"

[observability.logs]
enabled = true